#!/bin/sh

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Script to set up files to run in dev environment
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# One time set-up things
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Delete exiting symlink (if exisits)
#sudo [ -e /var/www/html] && sudo rm -r /var/www/html

# Create new symlink
#sudo ln -s /user/ec2-user/code/JRPL/JRPL-WC2014 /var/www/html

# Set correct ownership and permissions on symlink
#sudo chown -h root:www /var/www/html

# Main code
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Navigate to root directory
cd ~/code/JRPL/JRPL-WC2014/

# Change ownership of all files
sudo chown -R ec2-user:www .

# Change permissions of all files
find . -type f -exec chmod 640 {} \;
find . -type d -exec chmod 750 {} \;

# Make scripts executable
chmod 740 dev-setup

# Change DB access
sed -i "s:^\$link = mysqli_connect.*:\$link = mysqli_connect('localhost', 'root', '8@xgT54^1n');:" ~/code/JRPL/JRPL-WC2014/includes/db.inc.php
